layout_spectrum: 0.1713212
typography_spectrum: 0.1058002
color:
  saturation: 1
  lightness: 1
  brandStrength: 0
  rhythmicContrast: 0.4391139
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: The Williamsons
